Summary:	Common dirs for Perl modules
Name:		perl-dirs
Version:	1.0
Release:	4
License:	Public Domain
Group:		Development/Languages/Perl
Requires:	%{perl_vendorarch}
Requires:	%{perl_vendorlib}
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Common dirs for Perl modules.

%prep

%install
rm -rf $RPM_BUILD_ROOT
PVARCH="%{perl_vendorarch}"
PVLIB="%{perl_vendorlib}"
install -d $RPM_BUILD_ROOT{$PVARCH,$PVLIB}

while read dir; do
	install -d $RPM_BUILD_ROOT$dir
done <<EOF
$PVARCH/AI
$PVARCH/Algorithm
$PVARCH/Astro
$PVARCH/Audio
$PVARCH/Authen
$PVARCH/B
$PVARCH/BSD
$PVARCH/Bit
$PVARCH/Chemistry
$PVARCH/Class
$PVARCH/Compress
$PVARCH/Convert
$PVARCH/Crypt
$PVARCH/Crypt/OpenSSL
$PVARCH/Data
$PVARCH/DateTime
$PVARCH/Devel
$PVARCH/Device
$PVARCH/Digest
$PVARCH/File
$PVARCH/IPC
$PVARCH/Image
$PVARCH/Inline
$PVARCH/Linux
$PVARCH/Locale
$PVARCH/Math
$PVARCH/Math/BigInt
$PVARCH/Net
$PVARCH/Ogg
$PVARCH/Ogg/Vorbis
$PVARCH/PerlIO
$PVARCH/Speech
$PVARCH/Speech/Recognizer
$PVARCH/String
$PVARCH/Sys
$PVARCH/Template
$PVARCH/Term
$PVARCH/Text
$PVARCH/Time
$PVARCH/Unicode
$PVARCH/WWW
$PVARCH/XML
$PVARCH/auto/AI
$PVARCH/auto/Algorithm
$PVARCH/auto/Astro
$PVARCH/auto/Audio
$PVARCH/auto/Authen
$PVARCH/auto/BSD
$PVARCH/auto/Bit
$PVARCH/auto/Chemistry
$PVARCH/auto/Class
$PVARCH/auto/Clone
$PVARCH/auto/Compress
$PVARCH/auto/Convert
$PVARCH/auto/Crypt
$PVARCH/auto/Crypt/OpenSSL
$PVARCH/auto/Data
$PVARCH/auto/Devel
$PVARCH/auto/Device
$PVARCH/auto/Digest
$PVARCH/auto/File
$PVARCH/auto/IPC
$PVARCH/auto/Image
$PVARCH/auto/Inline
$PVARCH/auto/Linux
$PVARCH/auto/Locale
$PVARCH/auto/Math
$PVARCH/auto/Math/BigInt
$PVARCH/auto/Net
$PVARCH/auto/Ogg
$PVARCH/auto/Ogg/Vorbis
$PVARCH/auto/PerlIO
$PVARCH/auto/Regexp
$PVARCH/auto/Speech
$PVARCH/auto/Speech/Recognizer
$PVARCH/auto/String
$PVARCH/auto/Sys
$PVARCH/auto/Term
$PVARCH/auto/Text
$PVARCH/auto/Time
$PVARCH/auto/Unicode
$PVARCH/auto/WWW
$PVARCH/auto/XML
$PVLIB/AI
$PVLIB/AI/NeuralNet
$PVLIB/Algorithm
$PVLIB/Apache
$PVLIB/Apache2
$PVLIB/App
$PVLIB/App/Packer
$PVLIB/Archive
$PVLIB/Array
$PVLIB/Astro
$PVLIB/Attribute
$PVLIB/Audio
$PVLIB/Authen
$PVLIB/B
$PVLIB/Barcode
$PVLIB/Bundle
$PVLIB/Business
$PVLIB/CGI
$PVLIB/Cache
$PVLIB/Carp
$PVLIB/Chart
$PVLIB/Cisco
$PVLIB/Class
$PVLIB/Class/Data
$PVLIB/Config
$PVLIB/Convert
$PVLIB/Crypt
$PVLIB/DBD
$PVLIB/DNS
$PVLIB/Data
$PVLIB/Date
$PVLIB/Date/Japanese
$PVLIB/DateTime
$PVLIB/Devel
$PVLIB/Device
$PVLIB/Digest
$PVLIB/Email
$PVLIB/Email/Simple
$PVLIB/Error
$PVLIB/Exporter
$PVLIB/ExtUtils
$PVLIB/File
$PVLIB/File/Path
$PVLIB/Filesys
$PVLIB/Font
$PVLIB/Games
$PVLIB/Getopt
$PVLIB/GnuPG
$PVLIB/Graph
$PVLIB/Graphics
$PVLIB/HTML
$PVLIB/HTTP
$PVLIB/Hash
$PVLIB/I18N
$PVLIB/IO
$PVLIB/IO/Socket
$PVLIB/IPC
$PVLIB/Image
$PVLIB/Inline
$PVLIB/Jabber
$PVLIB/Language
$PVLIB/Lingua
$PVLIB/Lingua/EN
$PVLIB/Lingua/Stem
$PVLIB/Lingua/Stem/Snowball
$PVLIB/List
$PVLIB/Locale
$PVLIB/LockFile
$PVLIB/Log
$PVLIB/MIME
$PVLIB/Mail
$PVLIB/Math
$PVLIB/Math/BigInt
$PVLIB/Math/Business
$PVLIB/Math/Calc
$PVLIB/Math/Fractal
$PVLIB/Modem
$PVLIB/Module
$PVLIB/Net
$PVLIB/Net/IDN
$PVLIB/Net/SMTP
$PVLIB/NetAddr
$PVLIB/NetServer
$PVLIB/Netscape
$PVLIB/News
$PVLIB/Number
$PVLIB/OLE
$PVLIB/Object
$PVLIB/PAR
$PVLIB/PHP
$PVLIB/Params
$PVLIB/Parse
$PVLIB/PerlIO
$PVLIB/PerlIO/via
$PVLIB/Pod
$PVLIB/PostScript
$PVLIB/Proc
$PVLIB/Quantum
$PVLIB/RADIUS
$PVLIB/RPC
$PVLIB/RPM
$PVLIB/RTF
$PVLIB/Regexp
$PVLIB/SNMP
$PVLIB/SOAP
$PVLIB/SOAP/Transport
$PVLIB/SQL
$PVLIB/SVN
$PVLIB/Schedule
$PVLIB/Set
$PVLIB/Sort
$PVLIB/Speech
$PVLIB/Spreadsheet
$PVLIB/Statistics
$PVLIB/String
$PVLIB/Sub
$PVLIB/Sys
$PVLIB/TeX
$PVLIB/Template
$PVLIB/Term
$PVLIB/Term/ReadLine
$PVLIB/Term/Screen
$PVLIB/Test
$PVLIB/Text
$PVLIB/Text/Query
$PVLIB/Tie
$PVLIB/Time
$PVLIB/Tree
$PVLIB/UNIVERSAL
$PVLIB/Unicode
$PVLIB/Unix
$PVLIB/WWW
$PVLIB/WWW/Google
$PVLIB/X500
$PVLIB/XML
$PVLIB/XML/Filter
$PVLIB/XML/Handler
$PVLIB/XML/Parser
$PVLIB/XML/RSS
$PVLIB/XML/XPath
$PVLIB/auto
$PVLIB/auto/AI
$PVLIB/auto/Array
$PVLIB/auto/Config
$PVLIB/auto/Crypt
$PVLIB/auto/Data
$PVLIB/auto/Devel
$PVLIB/auto/GnuPG
$PVLIB/auto/Mail
$PVLIB/auto/Math
$PVLIB/auto/Net
$PVLIB/auto/Schedule
$PVLIB/auto/Statistics
$PVLIB/auto/Text
$PVLIB/auto/WWW
EOF

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%{perl_vendorlib}/*
%{perl_vendorarch}/*
%exclude %dir %{perl_vendorarch}/auto
